addons:
  sonarcloud:
    organization: "welldoer-github"
    token:
      secure: "0ba4ffd297c96098863aa26a8c6b56166f0866a7"

language: java

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - gradle check
  - sonar-scanner
